name: ARM Ubuntu Workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-arm:
    runs-on: ubuntu-22.04-arm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Display system information
      run: |
        echo "=== System Information ==="
        uname -a
        echo ""
        echo "=== CPU Architecture ==="
        lscpu | grep Architecture
        echo ""
        echo "=== CPU Model ==="
        lscpu | grep "Model name" || echo "Model name not available"
        echo ""
        echo "=== Memory Information ==="
        free -h
        echo ""
        echo "=== Disk Space ==="
        df -h /
        
    - name: Test ARM-specific commands
      run: |
        echo "=== Testing ARM Environment ==="
        echo "Architecture: $(uname -m)"
        echo "Processor: $(uname -p)"
        echo ""
        echo "=== Available packages test ==="
        which gcc && gcc --version | head -1 || echo "GCC not available"
        which python3 && python3 --version || echo "Python3 not available"
        which node && node --version || echo "Node.js not available"
        
    - name: Simple build test
      run: |
        echo "=== Simple Build Test ==="
        echo '#include <stdio.h>' > test.c
        echo 'int main() {' >> test.c
        echo '    printf("Hello from ARM Ubuntu 22.04!\\n");' >> test.c
        echo '    return 0;' >> test.c
        echo '}' >> test.c
        echo ""
        echo "=== Compiling test program ==="
        gcc test.c -o test_arm || echo "Compilation failed"
        if [ -f test_arm ]; then
          echo "=== Running test program ==="
          ./test_arm
          echo "=== File info ==="
          file test_arm
        else
          echo "Test program not created"
        fi